version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ALLOW_NONE_AUTHENTICATION=yes
    command: >
      /usr/local/bin/etcd
      --name etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - milvus-network

  minio:
    image: minio/minio:RELEASE.2023-06-23T20-26-00Z
    container_name: minio
    command: server /minio_data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/minio_data
    networks:
      - milvus-network

  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: milvus
    depends_on:
      - etcd
      - minio
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "19121:19121"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    networks:
      - milvus-network

volumes:
  minio_data:

networks:
  milvus-network:
    driver: bridge
